# platform/argocd-ingress/overlays/prod/kustomization.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  labels:
    env: prod
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.lab.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                name: http
