# apps/world-cup-ladder/overlays/prod/patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-cup-ladder
  labels:
    env: prod
spec:
  template:
    spec:
      containers:
        - name: world-cup-ladder
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
