# platform/monitoring/grafana/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

namespace: monitoring

patches:
  - path: patch.yaml