# platform/argocd/overlays/prod/patch.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    env: prod
spec:
  destination:
    namespace: argocd

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.14
      helm:
        valueFiles:
          - $values/platform/argocd/base/values.yaml
          - $values/platform/argocd/overlays/prod/values.yaml

    - repoURL: git@github.com:MagmaOps/k3s-lab.git
      targetRevision: refs/heads/main
      ref: values
