# platform/argocd/base/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.3.5
      helm:
        valueFiles:
          - $values/platform/argocd/base/values.yaml

    - repoURL: git@github.com:dmytro-zelenianskyi/k8s-lab.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: ARGOCD_NAMESPACE

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
