# platform/nginx/values.yaml
controller:
  replicaCount: 1

  ingressClassResource:
    name: nginx
    enabled: true
    default: false

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.240

  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: monitoring
      additionalLabels:
        release: kube-prometheus-stack

defaultBackend:
  enabled: false
