# apps/arc/base/arc-runner-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.14.2
      helm:
        valueFiles:
          - $values/apps/arc/base/runner-values.yaml

    - repoURL: git@github.com:MagmaOps/k3s-lab.git
      targetRevision: refs/heads/main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
