# apps/arc/base/runner-values.yaml
githubConfigUrl: https://github.com/MagmaOps

githubConfigSecret: arc-github-token

runnerScaleSetName: arc-runners

minRunners: 1
maxRunners: 4

controllerServiceAccount:
  name: arc-controller-gha-rs-controller
  namespace: arc-systems

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command:
          - /home/runner/run.sh
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
