# .github/workflows/main-pr.yml

name: Main pr validate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  ci:
    uses: MagmaOps/k3s-lab-ci/.github/workflows/k3s-validate.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
